import easyocr
import fitz          # PyMuPDF  — for PDFs
import docx          # python-docx — for Word files
import os
import re
from preprocess import (
    preprocess,
    load_image_from_path,
    convert_pdf_page_to_image,
    is_handwritten,
)


# ─────────────────────────────────────────────
# EasyOCR READER (load once, reuse)
# ─────────────────────────────────────────────

reader = easyocr.Reader(['en'], gpu=False)


# ─────────────────────────────────────────────
# 1. EXTRACT FROM IMAGE (JPG / PNG)
# ─────────────────────────────────────────────

def extract_from_image(image_path):
    """
    Handles:
    - Printed lab reports  (photo)
    - Handwritten prescriptions (photo)
    """
    print("File type: Image")

    image       = load_image_from_path(image_path)
    handwritten = is_handwritten(image)
    print(f"  Handwritten detected: {handwritten}")

    clean_image = preprocess(image, is_handwrite=handwritten)

    results  = reader.readtext(clean_image)
    raw_text = " ".join([
        text for (_, text, confidence) in results
        if confidence > 0.3   # lower threshold handles handwritten better
    ])

    return raw_text, "image", handwritten


# ─────────────────────────────────────────────
# 2. EXTRACT FROM PDF
# ─────────────────────────────────────────────

def extract_from_pdf(pdf_path):
    """
    Handles:
    - Digital PDF (typed/generated by hospital) → direct text extraction
    - Scanned PDF (photo inside PDF)            → OCR on each page
    """
    print("File type: PDF")

    pdf      = fitz.open(pdf_path)
    all_text = ""
    pdf_type = "digital"

    for page_num in range(len(pdf)):
        page      = pdf[page_num]
        page_text = page.get_text().strip()

        if len(page_text) > 20:
            # ── Digital PDF: real text exists inside ──
            print(f"  Page {page_num + 1}: Digital — direct extract")
            all_text += page_text + "\n"
            pdf_type  = "digital"

        else:
            # ── Scanned PDF: no text, render as image and OCR ──
            print(f"  Page {page_num + 1}: Scanned — using OCR")
            image       = convert_pdf_page_to_image(pdf_path, page_num)
            handwritten = is_handwritten(image)
            clean       = preprocess(image, is_handwrite=handwritten)
            results     = reader.readtext(clean)
            page_text   = " ".join([
                text for (_, text, conf) in results if conf > 0.3
            ])
            all_text += page_text + "\n"
            pdf_type  = "scanned"

    return all_text.strip(), pdf_type, False


# ─────────────────────────────────────────────
# 3. EXTRACT FROM WORD (.docx)
# ─────────────────────────────────────────────

def extract_from_word(docx_path):
    """
    Word documents have real text — no OCR needed.
    Direct paragraph extraction.
    """
    print("File type: Word Document")

    doc      = docx.Document(docx_path)
    all_text = "\n".join([
        para.text for para in doc.paragraphs
        if para.text.strip()
    ])

    return all_text.strip(), "word", False


# ─────────────────────────────────────────────
# CLEAN RAW TEXT
# ─────────────────────────────────────────────

def clean_text(raw_text):
    """
    Basic text cleaning after OCR:
    - Remove extra spaces
    - Remove non-printable characters
    - Fix common OCR mistakes in medical text
    """
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', raw_text).strip()

    # Remove non-printable characters
    text = re.sub(r'[^\x20-\x7E]', '', text)

    # Common OCR mis-reads in medical reports
    text = text.replace('G1ucose',      'Glucose')
    text = text.replace('He1moglobin',  'Hemoglobin')
    text = text.replace('0ral',         'Oral')
    text = text.replace('mg/d1',        'mg/dL')

    return text


# ─────────────────────────────────────────────
# MAIN FUNCTION — Called by Person 2 (FastAPI)
# ─────────────────────────────────────────────

def process_file(file_path):
    """
    This is the ONLY function Person 2 needs to call.

    Flow:
    - Person 2 fetches file_path from DB
    - Calls this function
    - Gets raw_text back
    - Saves raw_text to DB

    Parameters:
    - file_path : path to the file (from DB)

    Returns:
    - Dictionary with raw_text and metadata
      Person 2 saves this back to DB
    """

    print(f"\n{'='*50}")
    print(f"Processing file: {file_path}")
    print(f"{'='*50}")

    ext = os.path.splitext(file_path)[1].lower()

    # ── Route to correct extractor based on file type ──
    if ext in ['.jpg', '.jpeg', '.png', '.bmp', '.tiff']:
        raw_text, source_type, handwritten = extract_from_image(file_path)

    elif ext == '.pdf':
        raw_text, source_type, handwritten = extract_from_pdf(file_path)

    elif ext == '.docx':
        raw_text, source_type, handwritten = extract_from_word(file_path)

    else:
        raise ValueError(f"Unsupported file type: {ext}")

    # ── Clean the extracted text ──
    cleaned_text = clean_text(raw_text)

    print(f"\nExtracted Text Preview:\n{cleaned_text[:300]}...\n")

    # ── Return to Person 2 — they handle saving to DB ──
    return {
        "raw_text"    : cleaned_text,   # ← Person 2 saves this to DB
        "source_type" : source_type,    # image / digital / scanned / word
        "handwritten" : handwritten,    # True / False
        "status"      : "success"
    }


# ─────────────────────────────────────────────
# TEST — Run directly to verify
# ─────────────────────────────────────────────

if __name__ == "__main__":

    # Change this to any file in data/samples/
    test_file = "../data/samples/test_report_01.jpg"

    if os.path.exists(test_file):
        result = process_file(test_file)
        print("\nResult:")
        print(f"  Status      : {result['status']}")
        print(f"  Source Type : {result['source_type']}")
        print(f"  Handwritten : {result['handwritten']}")
        print(f"  Text Preview: {result['raw_text'][:200]}")
    else:
        print(f"Test file not found: {test_file}")
        print("Add a sample image to data/samples/ and try again.")